### PR TITLE
Fix missing redis commands

### PR DESCRIPTION
**Pull request by LoicMahieu**

### CODE REVIEW

**Comment by linus** [comment]
Thanks! I may have to revisit this and add any new commands as well - though I think the (newish) ioredis module has built-in support for prefixes.

**Comment by LoicMahieu** [comment]
Thanks. Yes indeed ioredis supports prefix: https://github.com/luin/ioredis#transparent-key-prefixing
I had to support a old project, refix was a good solution :+1: :)
Could you please publish the version 0.1.4 ?
Note: there is a version number in the readme, it is already not correct. In my opinion, just remove it from the package ;)

Thanks!

**Comment by linus** [comment]
Right,

I'm glad to hear. Of course I'll publish it.

On 2016-02-23 10:58, Loïc Mahieu wrote:
> Thanks. Yes indeed ioredis supports prefix: https://github.com/luin/ioredis#transparent-key-prefixing
> I had to support a old project, refix was a good solution :+1: :)
> Could you please publish the version 0.1.4 ?
> Note: there is a version number in the readme, it is already not correct. In my opinion, just remove it from the package ;)
> 
> Thanks!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linus/refix/pull/3#issuecomment-187631073
> 

-- 
http://yesbabyyes.se/
+46 709 89 03 85

**Comment by linus** [comment]
And 0.1.4 is published!

On 2016-02-23 10:58, Loïc Mahieu wrote:
> Thanks. Yes indeed ioredis supports prefix: https://github.com/luin/ioredis#transparent-key-prefixing
> I had to support a old project, refix was a good solution :+1: :)
> Could you please publish the version 0.1.4 ?
> Note: there is a version number in the readme, it is already not correct. In my opinion, just remove it from the package ;)
> 
> Thanks!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linus/refix/pull/3#issuecomment-187631073
> 

-- 
http://yesbabyyes.se/
+46 709 89 03 85

**Pull request merged**
